### PR TITLE
fix: display HTTPS interactions in client output

### LINKED ISSUE #1354: interactsh-client shows http interactions but not https
### Current Behavior:

When you run the client on your own server with:

```sh
 interactsh-client -server myserver.com -token mytoken
```

It will show **http** interactions but not **https** interactions.

### Expected Behavior:

I am expected to see both, in the caido plugin or if you use the -json flag you do see them. Also if you use one of the public servers, but I guess that's because everything is logged as http there?

### Extra info

At first I thought I had a misconfiguration so I was debugging my setup with copilot. I am not familiar with the code base but copilot said the bug is probably on this line:

https://github.com/projectdiscovery/interactsh/blob/main/cmd/interactsh-client/main.go#L226

It should be both "http" and "https".

I saw that there was a release recently (1.3.1) and the change log pointed out that the server now differentiates between "http" and "https":

https://github.com/projectdiscovery/interactsh/blob/main/pkg/server/http_server.go#L201

I guess that's where the bug happened? Again I stumbled my way through this with copilot without having a firm grasp on the code base so forgive me if my assumptions are incorrect.

### PR DESCRIPTION
**Pull request by dogancanbakir**
Fixes #1354

## Summary by CodeRabbit

* **Bug Fixes**
  * CLI non-JSON output now recognizes and displays both HTTP and HTTPS interactions, with accurate protocol labels in terminal output.

* **Documentation**
  * Clarified help text: the JSON output flag now refers to “JSON Lines format.”
  * Help and examples updated to note that the HTTP-only option reports both HTTP and HTTPS interactions in verbose output.

### CODE REVIEW

File: cmd/interactsh-client/main.go [hunk 1]
```diff
@@ -223,7 +223,7 @@ func main() {
 					}
 					writeOutput(outputFile, builder)
 				}
-			case "http":
+			case "http", "https":
 				if noFilter || cliOptions.HTTPOnly {
 					fmt.Fprintf(builder, "[%s] Received HTTP interaction from %s at %s", interaction.FullId, interaction.RemoteAddress, interaction.Timestamp.Format("2006-01-02 15:04:05"))
```
Comment (jentfoo) [inline cmd/interactsh-client/main.go]:
```suggestion
					fmt.Fprintf(builder, "[%s] Received %s interaction from %s at %s", interaction.FullId, strings.ToUpper(interaction.Protocol), interaction.RemoteAddress, interaction.Timestamp.Format("2006-01-02 15:04:05"))
```

**Review by Mzack9999 — APPROVED** [review]
